CREATE TABLE authors(
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    first_name VARCHAR(36) NOT NULL,
    last_name VARCHAR(36) NOT NULL
);
CREATE TABLE books(
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    title VARCHAR(36) NOT NULL,
    author_id VARCHAR(36) NOT NULL REFERENCES authors (id)
);

